### ISSUE TITLE
Cannot set text of a text area.

### ISSUE THREAD

**Issue by airyy** [dtylman/gowd#11]
Hello,

First off, I would like to say that I am glad I found this library because I really like it.

Now, my issue is that whenever I try and set the text of a textarea element using `element.SetText()`, it will clear all my elements(the body). I am not sure why this happens but thought that maybe you could look into it.

Thanks!

**Comment by dtylman** [comment]
Hi & thanks!

I was not able to reproduce this. Can you share a code sample?

This code seems to be working:
```go
b := new(body)
	b.Element = bootstrap.NewContainer(true)

	b.area = b.AddElement(gowd.NewElement("TextArea"))
	b.area.SetText("lala")
```
