### ISSUE TITLE
能否介绍一下在mac上怎么打包windows app

### ISSUE THREAD

**Issue by suifengqjn** [dtylman/gowd#15]
我用的是mac，想要给mac ，liunx 和 window 打包程序，具体该怎么操作呢，感谢

**Comment by dtylman** [comment]
ראשית, עליך להדר את התוכנה עבור הסביבה המתאימה, למשל עבור חלונות:

```
GOOS=windows ; go build 
```

מעבר לכך, עליך לשנות בתוך הגאווה-סקריט ולודא שאתה קורא לקובץ המקופל בשמו הנכון

וזהו!

האריזה היא אותה האריזה בכל הפלטפורמות למיטב ידיעתי.

חוצמזה, אני  סוגר הקריאה הזאת מכוון שאין כאן שום דבר שאפשר לתקן.

בהצלחה!
