### ISSUE TITLE
<select> element on event changes to first option.

### ISSUE THREAD

**Issue by Demitroi** [dtylman/gowd#2]
I'm developing a GUI app on go

`div = gowd.NewElement("div")`
`div.AddHTML(`<select id="lstEmpresas"> <option>Seleccione...</option><option>100</option><option>200</option><option>300</option>`, b.em)`
`pnl.AddToBody(div)`
`b.em["lstEmpresas"].OnEvent(gowd.OnChange, b.onChangeLstEmpresa)`

i have 3 value in a select element, when the onchange event is called works and i can get de option... But when the event finishes, the option is changed to the first option.

How i can solve this issue?

**Comment by dtylman** [comment]
can you share a largest code-snippet with the event implementation?

**Comment by Demitroi** [comment]
`var body *gowd.Element

func main() {
	body = bootstrap.NewContainer(false)
	sm := gowd.NewElementMap()
	div := gowd.NewElement("div")
	div.AddHTML(`<select value="" id="selecter" style="width: 200px">
	<option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option>
	</select>`, sm)
	sm["selecter"].OnEvent(gowd.OnChange, sltChanged)
	body.AddElement(div)
	gowd.Run(body)
}

func sltChanged(sender *gowd.Element, event *gowd.EventElement) {
	body.AddElement(gowd.NewText(event.GetValue()))
	body.AddElement(gowd.NewElement("br"))

}`

Check it out
[https://justpaste.it/18xel](url)

That doesn't happen when the "sltChanged" is not called.

`//sm["selecter"].OnEvent(gowd.OnChange, sltChanged)`

Check it out
[https://justpaste.it/18xep](url)

**Comment by Demitroi** [comment]
I want that an option stays selected as the second link.

**Comment by dtylman** [comment]
looks like a bug

**Comment by dtylman** [comment]
the problem was that `<select>` was not considered as `input` tag and therefore its event data was not processed. 

The fix was both in `go` and the `js` code, here: https://github.com/dtylman/gowd/blob/master/cmd/template/main.js#L93

Make sure you update your javascript or use the new and fixed `js` fro template.
